### ISSUE TITLE
Delete Scroll

### ISSUE THREAD

**Issue by clement-margueritte** [Faysoil/LWT#1]
Hey dude !

You can remove the scroll by deleting the margin-top: 60px in your #app div.

```css
#app {
    font-family: Avenir,Helvetica,Arial,sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    /* margin-top: 60px; */
}
```
